### ISSUE TITLE
Stuck at octopi login:

### ISSUE THREAD

**Issue by billb60** [mcuadros/OctoPrint-TFT#68]

**Comment by billb60** [comment]
I installed every thing and did following

    Modifiy octoprint-tft configuration:
    sudo vi /etc/octoprint-tft-environment
    This two changes need to be done ...
    OCTOPRINT_HOST=http://localhost
    OCTOPRINT_APIKEY= enter your API key here
    Modify octoprint-tft service configuration:
    sudo vi /lib/systemd/system/octoprint-tft.services
    You need to change TFT output from 0 to 1:
    ExecStart=/usr/bin/xinit /usr/bin/OctoPrint-TFT -- :1 -nolisten tcp -nocursor
And reboot and all get is 
Raspbian GMU/Linux 9 octopi tty1
octopi login: _
That is and curser just keep flashing

**Comment by billb60** [comment]
This is journalctl -f -u octoprint-tft.service
-- Logs begin at Thu 2016-11-03 17:16:42 GMT. --
May 15 00:50:58 octopi xinit[1158]: (EE)
May 15 00:50:58 octopi xinit[1158]: Fatal server error:
May 15 00:50:58 octopi xinit[1158]: (EE) no screens found(EE)
May 15 00:50:58 octopi xinit[1158]: (EE)
May 15 00:50:58 octopi xinit[1158]: Please consult the The X.Org Foundation supp                                                                                        ort
May 15 00:50:58 octopi xinit[1158]:          at http://wiki.x.org
May 15 00:50:58 octopi xinit[1158]:  for help.
May 15 00:50:58 octopi xinit[1158]: (EE) Please also check the log file at "/var                                                                                        /log/Xorg.1.log" for additional information.
May 15 00:50:58 octopi xinit[1158]: (EE)
May 15 00:50:58 octopi xinit[1158]: (EE) Server terminated with error (1). Closi                                                                                        ng log file.
May 15 00:51:12 octopi xinit[1158]: /usr/bin/xinit: giving up
May 15 00:51:12 octopi xinit[1158]: /usr/bin/xinit: unable to connect to X serve                                                                                        r: Connection refused
May 15 00:51:12 octopi xinit[1158]: /usr/bin/xinit: server error
May 15 00:51:12 octopi systemd[1]: octoprint-tft.service: Main process exited, c                                                                                        ode=exited, status=1/FAILURE
- Logs begin at Thu 2016-11-03 17:16:42 GMT. --
May 15 00:50:58 octopi xinit[1158]: (EE)
May 15 00:50:58 octopi xinit[1158]: Fatal server error:
May 15 00:50:58 octopi xinit[1158]: (EE) no screens found(EE)
May 15 00:50:58 octopi xinit[1158]: (EE)
May 15 00:50:58 octopi xinit[1158]: Please consult the The X.Org Foundation supp                                                                                        ort
May 15 00:50:58 octopi xinit[1158]:          at http://wiki.x.org
May 15 00:50:58 octopi xinit[1158]:  for help.
May 15 00:50:58 octopi xinit[1158]: (EE) Please also check the log file at "/var                                                                                        /log/Xorg.1.log" for additional information.
May 15 00:50:58 octopi xinit[1158]: (EE)
May 15 00:50:58 octopi xinit[1158]: (EE) Server terminated with error (1). Closi                                                                                        ng log fileMay 15 00:51:17 octopi disablescreenblank.sh[1159]: /usr/bin/xset:  u                                                                                        nable to open display ":0"
May 15 00:51:17 octopi disablescreenblank.sh[1159]: /usr/bin/xset:  unable to op                                                                                        en display ":0"
May 15 00:51:18 octopi disablescreenblank.sh[1159]: /usr/bin/xset:  unable to op                                                                                        en display ":0"
May 15 00:51:18 octopi systemd[1]: octoprint-tft.service: Control process exited                                                                                        , code=exited status=1
May 15 00:51:18 octopi systemd[1]: Failed to start OctoPrint-TFT.
May 15 00:51:18 octopi systemd[1]: octoprint-tft.service: Unit entered failed st                                                                                        ate.
May 15 00:51:18 octopi systemd[1]: octoprint-tft.service: Failed with result 'ex                                                                                        it-code'.
May 15 00:51:19 octopi systemd[1]: octoprint-tft.service: Service hold-off time                                                                                         over, scheduling restart.
May 15 00:51:19 octopi systemd[1]: Stopped OctoPrint-TFT.
May 15 00:51:19 octopi systemd[1]: Starting OctoPrint-TFT...
May 15 00:51:19 octopi xinit[1170]: X.Org X Server 1.19.2
May 15 00:51:19 octopi xinit[1170]: Release Date: 2017-03-02
May 15 00:51:19 octopi xinit[1170]: X Protocol Version 11, Revision 0
May 15 00:51:19 octopi xinit[1170]: Build Operating System: Linux 4.9.41-v7+ arm                                                                                        v7l Raspbian
May 15 00:51:19 octopi xinit[1170]: Current Operating System: Linux octopi 4.14.                                                                                        79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l
May 15 00:51:19 octopi xinit[1170]: Kernel command line: 8250.nr_uarts=0 bcm2708                                                                                        _fb.fbwidth=640 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3e                                                                                        c00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 con                                                                                        sole=tty1 root=PARTUUID=ba49a66b-02 rootfstype=ext4 elevator=deadline fsck.repai                                                                                        r=yes rootwait fbcon=map:10 fbcon=font:ProFont6x11 quiet splash plymouth.ignore-                                                                                        serial-consoles
May 15 00:51:19 octopi xinit[1170]: Build Date: 18 October 2017  04:55:30PM
May 15 00:51:19 octopi xinit[1170]: xorg-server 2:1.19.2-1+rpt1+deb9u2 (https://                                                                                        www.debian.org/support)
May 15 00:51:19 octopi xinit[1170]: Current version of pixman: 0.34.0
May 15 00:51:19 octopi xinit[1170]:         Before reporting problems, check htt                                                                                        p://wiki.x.org
May 15 00:51:19 octopi xinit[1170]:         to make sure that you have the lates                                                                                        t version.
May 15 00:51:19 octopi xinit[1170]: Markers: (--) probed, (**) from config file,                                                                                         (==) default setting,
May 15 00:51:19 octopi xinit[1170]:         (++) from command line, (!!) notice,                                                                                         (II) informational,
May 15 00:51:19 octopi xinit[1170]:         (WW) warning, (EE) error, (NI) not i                                                                                        mplemented, (??) unknown.
May 15 00:51:19 octopi xinit[1170]: (==) Log file: "/var/log/Xorg.1.log", Time:                                                                                         Wed May 15 00:51:19 2019
May 15 00:51:19 octopi xinit[1170]: (==) Using config directory: "/etc/X11/xorg.                                                                                        conf.d"
May 15 00:51:19 octopi xinit[1170]: (==) Using system config directory "/usr/sha                                                                                        re/X11/xorg.conf.d"
May 15 00:51:19 octopi xinit[1170]: Parse error on line 1 of section InputClass                                                                                         in file /usr/share/X11/xorg.conf.d/99-pitft.conf
May 15 00:51:19 octopi xinit[1170]:         The Section keyword requires a quote                                                                                        d string to follow it.

**Comment by fchansa** [comment]
Same here :-(
The hole screen refreshes - 1s console - 2s black ... and so on.

**Comment by brightblack** [comment]
hmm. I may or may not've had the same problem.. in my case it seems to be cause by a panic on /home/pi/style.css not being present.

I 'touched' the location to make something present and now it at least kind of starts.. although it looks ugly.. and i can see I have other kinks to workout.

I found the issue by trying to manually run the commands I could see in /lib/systemd/system/octoprint-tft.service

pi@octopi:~ $ sudo /usr/bin/xinit /usr/bin/OctoPrint-TFT -- :0 -nolisten tcp -nocursor


X.Org X Server 1.19.3
Release Date: 2017-03-15
X Protocol Version 11, Revision 0
Build Operating System: Linux 4.4.0-97-generic armv7l Ubuntu
Current Operating System: Linux octopi 4.19.42-v7+ #1219 SMP Tue May 14 21:20:58 BST 2019 armv7l
Kernel command line: coherent_pool=1M 8250.nr_uarts=1 bcm2708_fb.fbwidth=1024 bcm2708_fb.fbheight=600 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=ttyS0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait fbcon=map:10 fbcon=font:ProFont6x11 logo.nologo
Build Date: 13 October 2017  01:52:36PM
xorg-server 2:1.19.3-1ubuntu1.3 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.34.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sun Jun  9 08:57:26 2019
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
INFO[0000] Found API key at "/home/pi/.octoprint/config.yaml" file  file=main.go func=main.init.1 line=45
panic: <broken file>:1:0Failed to import: Error opening file /home/pi/style.css: No such file or directory

goroutine 1 [running]:
github.com/mcuadros/OctoPrint-TFT/ui.MustCSSProviderFromFile(0x5328d6, 0x9, 0x557c60e0)
	/go/src/github.com/mcuadros/OctoPrint-TFT/obj-arm-linux-gnueabihf/src/github.com/mcuadros/OctoPrint-TFT/ui/gtk.go:161 +0xe4
github.com/mcuadros/OctoPrint-TFT/ui.(*UI).loadStyle(0x557bfac0)
	/go/src/github.com/mcuadros/OctoPrint-TFT/obj-arm-linux-gnueabihf/src/github.com/mcuadros/OctoPrint-TFT/ui/ui.go:76 +0x24
github.com/mcuadros/OctoPrint-TFT/ui.(*UI).initialize(0x557bfac0)
	/go/src/github.com/mcuadros/OctoPrint-TFT/obj-arm-linux-gnueabihf/src/github.com/mcuadros/OctoPrint-TFT/ui/ui.go:58 +0x48
github.com/mcuadros/OctoPrint-TFT/ui.New(0x5351bc, 0x10, 0x557c79e0, 0x20, 0x5583b902)
	/go/src/github.com/mcuadros/OctoPrint-TFT/obj-arm-linux-gnueabihf/src/github.com/mcuadros/OctoPrint-TFT/ui/ui.go:52 +0x29c
main.main()
	/go/src/github.com/mcuadros/OctoPrint-TFT/obj-arm-linux-gnueabihf/src/github.com/mcuadros/OctoPrint-TFT/main.go:55 +0xa8
/usr/bin/xinit: connection to X server lost

waiting for X server to shut down (II) Server terminated successfully (0). Closing log file.
